version: '3.7'
services:
  web:
    build:
      dockerfile: ./Dockerfile
    links:
      - mysql
    ports:
      - '3000:3000'
    env_file:
      - .env
  mysql:
    image: mysql:8.0.35-debian
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: rdeveloper
      MYSQL_PASSWORD: rdeveloper
      MYSQL_DATABASE: breath_production
    volumes:
      - mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']

volumes:
  mysql:

