default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  reconnect: true
  timeout: 5000
  username: <%= ENV.fetch("DB_USERNAME", "rdeveloper") %>
  password: <%= ENV.fetch("DB_PASSWORD", "rdeveloper") %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "breath_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "breath_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "breath_production") %>

docker:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "breath_production") %>
  host: <%= ENV.fetch("DB_HOST", "mysql") %>
